### ISSUE TITLE
Fetch open PRs on startup

### ISSUE THREAD

**Issue by duijf** [channable/hoff#10]
Hoff should fetch open PRs on startup.

In https://github.com/channable/hoff/pull/8, we have closed and re-opened PRs in a loop to deliver new webhook events to Hoff. Hoff should be able to deal with those events gracefully.

Otherwise, Hoff will not know about PRs and will ignore `LGTM` comments on them. This is problematic because:

 - It means that we cannot easily restart hoff/have downtime.
 - Adopting Hoff on a repo that already had PRs open means opening/closing all of them.

**Comment by ruuda** [comment]
We have had one pull request in the "recently integrated" state for about a week now. I think we may have missed the webhook delivery of the close notification. This is not easy to fix, because we can’t re-open and close the pull request on Github. It is not that big of a deal, but it is causing an off-by-one in the queue status notification. One workaround would be to perform some manual surgery on the state file, but let's not do that, and just implement the proper fix. Then a restart of Hoff would make the outdated statuses go away.

I think what we can do is:

* Traverse all pull requests that exist in the state, and retrieve their status from GitHub. If they are closed, generate a [`PullRequestClosed` event](https://github.com/channable/hoff/blob/a4531e77843f6dfcb76edde60e6a57131ec9f7c9/src/Logic.hs#L158).
* Retrieve all open pull requests from GitHub. For those that are not present in the state, generate a [`PullRequestOpened` event](https://github.com/channable/hoff/blob/a4531e77843f6dfcb76edde60e6a57131ec9f7c9/src/Logic.hs#L153). For those that are present, generate a [`PullRequestCommitChanged` event](https://github.com/channable/hoff/blob/a4531e77843f6dfcb76edde60e6a57131ec9f7c9/src/Logic.hs#L157).

This should bring the status in sync again, without destroying existing approval status. I wouldn’t scan comments for now, if we missed an approval comment, it is easy enough to leave a new comment, and you can check the status in the webinterface.
