### ISSUE TITLE
Do not mark a PR as unmergable when CI fails

### ISSUE THREAD

**Issue by FPtje** [channable/hoff#214]
When merging a PR, the CI build might be flaky and fail. Currently, if you try to merge the PR again, Hoff will remind you of the last CI build failure. Hoff wants _something_ to change before you can merge the PR again.

IIRC this was originally a feature. The idea behind it, is that if your PR is bad, and CI fails, then it's not worth the effort trying again until something changes. The idea is that this prevents wasting valuable Hoff merging time.

The problem is, by far most of the attempted re-merges are because of flaky builds. It makes no sense for Hoff to block these, as retrying the merge will most likely succeed. In the end, the following flow is how we end up merging PRs where the build was flaky:

- Create PR
- Call Hoff to merge
- Wait for testing build
- Testing build fails due to flaky error
- Call hoff to merge again
  - Hoff says no, because a previous build failed
- Close the PR
- Hoff "abandons" the PR, this change opens up the possibility to merge again after reopening
- Reopen the PR
- Call hoff to merge again
- Testing succeeds
- PR is merged

Expected behavior is as follows:

- Create PR
- Call Hoff to merge
- Wait for testing build
- Testing build fails due to flaky error
- Call hoff to merge again
- Testing succeeds
- PR is merged

**Comment by gruhn** [comment]
Would automatically retrying the flaky job a few times be an option? As suggested here

https://stackoverflow.com/questions/71574593/how-to-automatically-retry-github-action-jobs-on-failure

**Comment by robbert-vdh** [comment]
I'll take a look at this. Having to close and reopen a PR when tests are flaky just to be able to retry merging is kind of annoying.

@gruhn Could you create a separate issue for automatically retrying failed tests?

**Comment by robbert-vdh** [comment]
So, the reason for why it's impossible to merge PRs once a check has failed right now is this function:

https://github.com/channable/hoff/blob/82053dd6fabf5f35853e90ee8ed697946db69956/src/Project.hs#L604-L607

The idea being that if Hoff receives multiple build status updates for a commit, previous success or failure statuses will never be overwritten. In practice this should never be an issue because the checks are either flaky, or they'll return the same status each time.

So to me it seems like these are some of the options:

1) Remove the `superseeds` concept entirely. That means new incoming build statuses will replace matching old build statuses. In theory a build could go from failing or succeeding to pending but that realistically won't happen in practice.
2) Modify `superseeds` to specifically allow failing builds to be superseded by successful builds but not the other way around. This is probably the desired behavior as it allows rerunning flaky tests without altering any other behavior.

An important detail to be aware of here is that the `@hoffbot merge` command does not directly result in Hoff performing a merge, but it instead merely indicates approval for merging and it integrates the PR into the merge train. The rebased PR is then as soon as the tests succeed. And since the current `superseeds`function does not allow build statuses to be overwritten, the only way to get the bot to retry merging the PR is to close and reopen the PR which lets you restart the whole sequence by running the merge command again. Rerunning the merge command after it has been run once currently only causes the bot to post another feedback comment ([here](https://github.com/channable/hoff/blob/82053dd6fabf5f35853e90ee8ed697946db69956/src/Logic.hs#L550-L556)). So there is also a third option, but that's going to involve adding a lot more moving parts:

3) Try to keep the current behavior as is, and only process the new successful build statuses when a merge command is invoked again. This involves spooling build statuses for integrated PRs that already have a 'final' build status (e.g. success or failure), and then only incorporating those build statuses once the merge command is repeated. The upside of this approach would be that it avoids the situation where someone triggers a rerun of a flaky CI job at a later time (say, during the weekend), causing the PR to suddenly gets merged.

Does anyone have a preference for an approach here?

**Comment by ruuda** [comment]
> In theory a build could go from failing or succeeding to pending but that realistically won't happen in practice.

I expect it will happen due to the way GitHub build statuses work, CI can be slow to inform GitHub that it has started building a particular commit, or people can restart a build on CI. Option 2 sounds safer to me. It also has a nice formal description, you can say that the status is a monoid or join semilattice, where `Pending < Failed < Succeeded`.
